---
#### Starting with creation of the Jenkins NAMESPACE
apiVersion: v1
kind: Namespace
metadata:
  name: devops-tools
  
---
  
# #### Creating the volume for data persistence
 apiVersion: v1
 kind: PersistentVolume
 metadata:
   name: jenkins-home
   namespace: devops-tools
 spec:
   accessModes:
     - ReadWriteOnce
   capacity:
     storage: 5Gi
   hostPath:
     path: /data/jenkins-home/
awsElasticBlockStore:  
  volumeID: aws://us-east-2a/vol-0f00c29607751a106
  fsType: xfs 