---
#### Starting with creation of the Jenkins NAMESPACE
apiVersion: v1
kind: Namespace
metadata:
  name: devops-tools

---
  
##### Creating the volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-data
  namespace: devops-tools
spec:
  storageClassName: cloud-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
