---
  
##### Creating the volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pvc
  namespace: devops-tools
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
      
---   
####How do we want it implemented      
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: jenkins-data
# provisioner: kubernetes.io/aws-ebs
# parameters:
#   type: gp2

--- 
#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata: 
#  name: efs-sc
#provisioner: efs.csi.aws.com
